CREATE TABLE arquivo_chamado( 
      id  integer generated by default as identity     NOT NULL , 
      name blob sub_type 1    NOT NULL , 
      chamado_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE atendente( 
      id  integer generated by default as identity     NOT NULL , 
      system_user_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE categoria( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      email blob sub_type 1    NOT NULL , 
      descricao blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE chamado( 
      id  integer generated by default as identity     NOT NULL , 
      solicitante_id integer    NOT NULL , 
      status_id integer    NOT NULL , 
      prioridade_id integer    NOT NULL , 
      produto_id integer    NOT NULL , 
      categoria_id integer    NOT NULL , 
      dt_abertura timestamp    NOT NULL , 
      observacao_abertura blob sub_type 1    NOT NULL , 
      atendente_id integer   , 
      tipo_problema_id integer   , 
      tipo_solucao_id integer   , 
      dt_fechamento timestamp   , 
      observacao_finalizacao blob sub_type 1   , 
      tempo_trabalho time   , 
      recorente char  (1)    DEFAULT 'F' , 
      mes_abertura blob sub_type 1   , 
      ano_abertura blob sub_type 1   , 
      anomes_abertura blob sub_type 1   , 
      ano_fechamento blob sub_type 1   , 
      mes_fechamento blob sub_type 1   , 
      anomes_fechamento integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cliente( 
      id  integer generated by default as identity     NOT NULL , 
      segmento_id integer    NOT NULL , 
      system_user_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE cliente_produto( 
      id  integer generated by default as identity     NOT NULL , 
      produto_id integer    NOT NULL , 
      cliente_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE nota( 
      id  integer generated by default as identity     NOT NULL , 
      observacao blob sub_type 1    NOT NULL , 
      dt_nota timestamp    NOT NULL , 
      chamado_id integer    NOT NULL , 
      cliente_id integer   , 
      atendente_id integer   , 
      anexo blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE prioridade( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      cor blob sub_type 1    NOT NULL , 
      ordem integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE produto( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      ativo char  (1)    DEFAULT 'T'  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE segmento( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE status( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      cor blob sub_type 1    NOT NULL , 
      estado_inicial char  (1)    DEFAULT 'F'  NOT NULL , 
      estado_final char  (1)    DEFAULT 'F'  NOT NULL , 
      ativo char  (1)    DEFAULT 'T'  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE template( 
      id  integer generated by default as identity     NOT NULL , 
      chave varchar  (255)    NOT NULL , 
      template blob sub_type 1    NOT NULL , 
      titulo blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_problema( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      ativo char  (1)    DEFAULT 'T'  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_solucao( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      ativo char  (1)    DEFAULT 'T'  NOT NULL , 
 PRIMARY KEY (id)) ; 

 
 CREATE UNIQUE INDEX unique_idx_template_chave ON template COMPUTED BY (chave);
  
 ALTER TABLE arquivo_chamado ADD CONSTRAINT fk_arquivo_chamado_1 FOREIGN KEY (chamado_id) references chamado(id); 
ALTER TABLE chamado ADD CONSTRAINT fk_chamado_1 FOREIGN KEY (solicitante_id) references cliente(id); 
ALTER TABLE chamado ADD CONSTRAINT fk_chamado_2 FOREIGN KEY (atendente_id) references atendente(id); 
ALTER TABLE chamado ADD CONSTRAINT fk_chamado_3 FOREIGN KEY (status_id) references status(id); 
ALTER TABLE chamado ADD CONSTRAINT fk_chamado_4 FOREIGN KEY (tipo_problema_id) references tipo_problema(id); 
ALTER TABLE chamado ADD CONSTRAINT fk_chamado_5 FOREIGN KEY (tipo_solucao_id) references tipo_solucao(id); 
ALTER TABLE chamado ADD CONSTRAINT fk_chamado_6 FOREIGN KEY (produto_id) references produto(id); 
ALTER TABLE chamado ADD CONSTRAINT fk_chamado_7 FOREIGN KEY (categoria_id) references categoria(id); 
ALTER TABLE chamado ADD CONSTRAINT fk_chamado_8 FOREIGN KEY (prioridade_id) references prioridade(id); 
ALTER TABLE cliente ADD CONSTRAINT fk_cliente_1 FOREIGN KEY (segmento_id) references segmento(id); 
ALTER TABLE cliente_produto ADD CONSTRAINT fk_cliente_produto_1 FOREIGN KEY (produto_id) references produto(id); 
ALTER TABLE cliente_produto ADD CONSTRAINT fk_cliente_produto_2 FOREIGN KEY (cliente_id) references cliente(id); 
ALTER TABLE nota ADD CONSTRAINT fk_nota_1 FOREIGN KEY (chamado_id) references chamado(id); 
ALTER TABLE nota ADD CONSTRAINT fk_nota_2 FOREIGN KEY (cliente_id) references cliente(id); 
ALTER TABLE nota ADD CONSTRAINT fk_nota_3 FOREIGN KEY (atendente_id) references atendente(id); 
